FM302 – NIST-Fortran78
FM302 Program
412 statements
Source File
Calls
Contents
Common Blocks
unnamed unnamed unnamed unnamed unnamed unnamed unnamed BLK1 BLK10 BLK2 BLK2 BLK3 BLK4 BLK5 BLK7 BLK8 BLK9 BLKCHR
Variables
CATN11 CVTN01 CVTN02 FF304
Common Blocks
common
Type Attributes Name Initial
integer :: IVCN01
common
Type Attributes Name Initial
real :: RVCN01//IVCN03
common
Type Attributes Name Initial
real :: // IACN11(4)
integer :: IVCN04
integer :: IVCN05
common
Type Attributes Name Initial
integer :: IVCN06 /BLK5/ RVCND1
integer :: IVCN08
integer :: LVCND1//IVCN07
common
Type Attributes Name Initial
integer :: IVCN06 /BLK6/ RVCNE1
common
Type Attributes Name Initial
integer :: IVCE09
common
Type Attributes Name Initial
integer :: IVCN12
common /BLK1/
Type Attributes Name Initial
integer :: IVCNA1
common /BLK10/
Type Attributes Name Initial
integer :: IVCNJ1
common /BLK2/
Type Attributes Name Initial
integer :: IVCNB1
real :: RVCNB1
common /BLK2/
Type Attributes Name Initial
integer :: IVCNB2
common /BLK3/
Type Attributes Name Initial
integer :: IVCNC1
integer :: LVCNC1
common /BLK4/
Type Attributes Name Initial
integer :: IACN21(2,3)
real :: RACN11
common /BLK5/
Type Attributes Name Initial
integer :: IVCND1
integer :: IVCND2
common /BLK7/
Type Attributes Name Initial
integer :: IACN1F
integer :: IVCNF1
integer :: IVCNF2
integer :: IVCNF3
common /BLK8/
Type Attributes Name Initial
integer :: IVCEH1
common /BLK9/
Type Attributes Name Initial
integer :: IVCEI1
common /BLKCHR/
Type Attributes Name Initial
real :: CATN11
real :: CVTN01
real :: CVTN02
Variables
Type Attributes Name Initial
character :: CATN11(3)*5
character :: CVTN01*2
character :: CVTN02*3
integer :: FF304
Call graph
fm302 calls 14, iacn11, iace1i, iacn21, fs303, racn11, iacn1f
fs303 calls iacn21, racn11, iacn1g