FM361 – NIST-Fortran78
FM361 Program
702 statements
Source File
**********00010361 * FORTRAN 77 00020361 FM361 XMAX - (165) 00030361 * 00040361 **********00050361 GENERAL PURPOSE SUBSET REF00060361 * TEST OF INTRINSIC FUNCTIONS AMAX0,AMAX1,MAX0,MAX1 15.3 00070361 CHOOSING LARGEST VALUE (TABLE 5)00080361 * 00090361 BB* **** BBCCOMNT *****00100361 00110361 1978 FORTRAN COMPILER VALIDATION SYSTEM 00120361 VERSION 2.1 00130361 00140361 00150361 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00160361 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00170361 SOFTWARE STANDARDS VALIDATION GROUP 00180361 BUILDING 225 RM A266 00190361 GAITHERSBURG, MD 20899 00200361 00210361 00220361 00230361 BE *** BBCCOMNT ******00240361 BB *** BBCINITA ******00250361 SPECIFICATION STATEMENTS 00260361 00270361 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00400361 FOR IDENTIFYING THE TEST ENVIRONMENT 00410361 00420361 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00430361 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00440361 Z03 ZPROG = 'PROGRAM NAME' 00450361 Z04 ZDATE = 'DATE OF TEST' 00460361 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00470361 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00480361 Z07 ZNAME = 'NAME OF USER' 00490361 Z08 ZTAPE = 'TAPE OWNER/ID' 00500361 Z09 ZTAPED = 'DATE TAPE COPIED' 00510361 00520361 00810361 WRITE REPORT TITLE 00820361 00830361 00910361 * HEADER FOR SEGMENT 165 00920361 WRITE DETAIL REPORT HEADERS 00990361 01000361 01070361 * TEST OF AMAX0 01080361 01090361 * 02820361 TEST OF AMAX1 02860361 * 02870361 04600361 * TEST OF MAX0 04640361 * 04650361 * 04680361 T025 TEST 25 BOTH VALUES ZERO 04690361 06270361 * TEST OF MAX1 06310361 06320361 * 07930361 BB* **** BBCSUM0 *****07940361 WRITE OUT TEST SUMMARY 07950361 07960361 WRITE OUT REPORT FOOTINGS 08080361 08090361 FORMATS FOR TEST DETAIL LINES 08150361 08160361 FORMAT STATEMENTS FOR PAGE HEADERS 08360361 08370361 08500361 FORMAT STATEMENTS FOR REPORT FOOTINGS 08510361 08520361 08570361 FORMAT STATEMENTS FOR RUN SUMMARY 08580361 08590361 08660361 *** END OF TEST SEGMENT 165 08670361
Calls
Contents
Variables
REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
character :: REMRKS*31
*** INITIALIZE SECTION 00320361
character :: ZCOMPL*20
*** INITIALIZE SECTION 00320361
character :: ZDATE*17
*** INITIALIZE SECTION 00320361
character :: ZNAME*20
*** INITIALIZE SECTION 00320361
character :: ZPROG*5
*** INITIALIZE SECTION 00320361
character :: ZPROJ*13
*** INITIALIZE SECTION 00320361
character :: ZTAPE*10
*** INITIALIZE SECTION 00320361
character :: ZTAPED*13
*** INITIALIZE SECTION 00320361
character :: ZVERS*13
*** INITIALIZE SECTION 00320361
character :: ZVERSD*17
*** INITIALIZE SECTION 00320361
Call graph
fm361 calls max1, amax0, amax1