FM362 – NIST-Fortran78
FM362 Program
691 statements
Source File
**********00010362 * FORTRAN 77 00020362 FM362 XMIN - (167) 00030362 * 00040362 **********00050362 GENERAL PURPOSE SUBSET REF00060362 * TEST INTRINSIC FUNCTIONS AMIN0,AMIN1,MIN0,MIN1 15.3 00070362 CHOOSING SMALLEST VALUE. (TABLE 5)00080362 * 00090362 BB* **** BBCCOMNT *****00100362 00110362 1978 FORTRAN COMPILER VALIDATION SYSTEM 00120362 VERSION 2.1 00130362 00140362 00150362 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00160362 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00170362 SOFTWARE STANDARDS VALIDATION GROUP 00180362 BUILDING 225 RM A266 00190362 GAITHERSBURG, MD 20899 00200362 00210362 00220362 00230362 BE *** BBCCOMNT ******00240362 BB *** BBCINITA ******00250362 SPECIFICATION STATEMENTS 00260362 00270362 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00400362 FOR IDENTIFYING THE TEST ENVIRONMENT 00410362 00420362 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00430362 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00440362 Z03 ZPROG = 'PROGRAM NAME' 00450362 Z04 ZDATE = 'DATE OF TEST' 00460362 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00470362 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00480362 Z07 ZNAME = 'NAME OF USER' 00490362 Z08 ZTAPE = 'TAPE OWNER/ID' 00500362 Z09 ZTAPED = 'DATE TAPE COPIED' 00510362 00520362 00810362 WRITE REPORT TITLE 00820362 00830362 00910362 * HEADER FOR SEGMENT 167 00920362 WRITE DETAIL REPORT HEADERS 00990362 01000362 01070362 * TEST OF AMIN0 01080362 01090362 * 02680362 TEST OF AMIN1 02720362 * 02730362 04460362 * TEST OF MIN0 04500362 04510362 * 06130362 TEST OF MIN1 06170362 * 06180362 * 07800362 BB *** BBCSUM0 ******07810362 WRITE OUT TEST SUMMARY 07820362 07830362 WRITE OUT REPORT FOOTINGS 07950362 07960362 FORMATS FOR TEST DETAIL LINES 08020362 08030362 FORMAT STATEMENTS FOR PAGE HEADERS 08230362 08240362 08370362 FORMAT STATEMENTS FOR REPORT FOOTINGS 08380362 08390362 08440362 FORMAT STATEMENTS FOR RUN SUMMARY 08450362 08460362 08530362 **** END OF TEST SEGMENT 167 08540362
Calls
Contents
Variables
REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
character :: REMRKS*31
*** INITIALIZE SECTION 00320362
character :: ZCOMPL*20
*** INITIALIZE SECTION 00320362
character :: ZDATE*17
*** INITIALIZE SECTION 00320362
character :: ZNAME*20
*** INITIALIZE SECTION 00320362
character :: ZPROG*5
*** INITIALIZE SECTION 00320362
character :: ZPROJ*13
*** INITIALIZE SECTION 00320362
character :: ZTAPE*10
*** INITIALIZE SECTION 00320362
character :: ZTAPED*13
*** INITIALIZE SECTION 00320362
character :: ZVERS*13
*** INITIALIZE SECTION 00320362
character :: ZVERSD*17
*** INITIALIZE SECTION 00320362
Call graph
fm362 calls amin0, amin1, min1