FM407 – NIST-Fortran78
FM407 Program
175 statements
Source File
**********00010407 * FORTRAN 77 00020407 FM407 00030407 * DIRAF1 - (410) 00040407 THIS PROGRAM CALLS SUBROUTINE SN408 00050407 **********00060407 * TESTING OF DIRECT ACCESS FILES SUBSET REF00070407 UNFORMATED RECORDS ONLY 12.10.1 00080407 * 00090407 00100407 BB *** BBCCOMNT ******00110407 00120407 1978 FORTRAN COMPILER VALIDATION SYSTEM 00130407 VERSION 2.1 00140407 00150407 00160407 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00170407 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00180407 SOFTWARE STANDARDS VALIDATION GROUP 00190407 BUILDING 225 RM A266 00200407 GAITHERSBURG, MD 20899 00210407 00220407 00230407 00240407 BE *** BBCCOMNT ******00250407 00260407 * S P E C I F I C A T I O N S SEGMENT 410 00270407 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00470407 FOR IDENTIFYING THE TEST ENVIRONMENT 00480407 00490407 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00500407 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00510407 Z03 ZPROG = 'PROGRAM NAME' 00520407 Z04 ZDATE = 'DATE OF TEST' 00530407 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00540407 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00550407 Z07 ZNAME = 'NAME OF USER' 00560407 Z08 ZTAPE = 'TAPE OWNER/ID' 00570407 Z09 ZTAPED = 'DATE TAPE COPIED' 00580407 00590407 * 00840407 THE FOLLOWING STATEMENT MUST BE CHANGED IF 00850407 * THE UNIT GIVEN IS NOT CAPABLE OF BEING OPENED AS A 00860407 DIRECT, UNFORMATTED FILE. 00870407 * 00880407 I10 CONTAINS THE UNIT NUMBER FOR A DIRECT, UNFORMATTED FILE. 00890407 00930407 * THE FOLLOWING STATEMENT MUST BE CHANGED IF THE NAME 00940407 GIVEN IS NOT A VALID FILE SPECIFIER FOR A DIRECT, 00950407 * UNFORMATTED FILE. 00960407 00970407 * 00980407 01030407 WRITE REPORT TITLE 01040407 01050407 * FILE NUMBER ASSIGNMENT 01130407 01150407 * HEADER FOR SEGMENT 410 01160407 WRITE DETAIL REPORT HEADERS 01210407 01220407 01290407 * 01350407 01370407 * WRITE 10 RECORDS IN SEQUENCE, REC = 1 TO 10 01390407 WRITE RECORDS NOT IN SEQUENCE OF RECORD NUMBER 01920407 * 02430407 BB* **** BBCSUM0 *****02710407 WRITE OUT TEST SUMMARY 02720407 02730407 WRITE OUT REPORT FOOTINGS 02850407 02860407 FORMATS FOR TEST DETAIL LINES 02920407 02930407 FORMAT STATEMENTS FOR PAGE HEADERS 03130407 03140407 03270407 FORMAT STATEMENTS FOR REPORT FOOTINGS 03280407 03290407 03340407 FORMAT STATEMENTS FOR RUN SUMMARY 03350407 03360407 03430407 * END OF TEST SEGMENT 410 03440407
Calls
Contents
Variables
A41K A4VK AVB B41K B4VK BVB C1B D1B REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
character(len=4) :: A41K(10)
character(len=4) :: A4VK
logical :: AVB
* BELOW CHARACTER STATEMENT ESTABLISHES THE FILE NAME VARIABLES. 00310407 BB* **** BBCINITA *****00320407 SPECIFICATION STATEMENTS 00330407 *** 00340407
character(len=4) :: B41K(10)
character(len=4) :: B4VK
logical :: BVB
* BELOW CHARACTER STATEMENT ESTABLISHES THE FILE NAME VARIABLES. 00310407 BB* **** BBCINITA *****00320407 SPECIFICATION STATEMENTS 00330407 *** 00340407
logical :: C1B(10)
* BELOW CHARACTER STATEMENT ESTABLISHES THE FILE NAME VARIABLES. 00310407 BB* **** BBCINITA *****00320407 SPECIFICATION STATEMENTS 00330407 *** 00340407
logical :: D1B(10)
* BELOW CHARACTER STATEMENT ESTABLISHES THE FILE NAME VARIABLES. 00310407 BB* **** BBCINITA *****00320407 SPECIFICATION STATEMENTS 00330407 *** 00340407
character :: REMRKS*31
*** INITIALIZE SECTION 00390407
character :: ZCOMPL*20
*** INITIALIZE SECTION 00390407
character :: ZDATE*17
*** INITIALIZE SECTION 00390407
character :: ZNAME*20
*** INITIALIZE SECTION 00390407
character :: ZPROG*5
*** INITIALIZE SECTION 00390407
character :: ZPROJ*13
*** INITIALIZE SECTION 00390407
character :: ZTAPE*10
*** INITIALIZE SECTION 00390407
character :: ZTAPED*13
*** INITIALIZE SECTION 00390407
character :: ZVERS*13
*** INITIALIZE SECTION 00390407
character :: ZVERSD*17
*** INITIALIZE SECTION 00390407
Call graph
fm407 calls m1i, l1i, sn408, f1s, k1i, g1s
sn408 calls mt1i, lt1i, kt1i