FM404 – NIST-Fortran78
FM404 Program
147 statements
Source File
**********00010404 * FORTRAN 77 00020404 FM404 AFMTS - (022) 00030404 * 00040404 **********00050404 GENERAL PURPOSE SUBSET REFS00060404 * TO TEST SIMPLE FORMAT AND FORMATTED DATA 12.9.5.200070404 TRANSFER STATEMENTS IN EXTERNAL SEQUENTIAL I/O SO 13.1.1 00080404 * THAT THESE FEATURES MAY BE USED IN OTHER TEST 12.8.1 00090404 PROGRAM SEGMENTS FOR CHARACTER DATA TYPES. 4.8 00100404 * 00110404 RESTRICTIONS OBSERVED 00120404 * * ALL FORMAT STATEMENTS ARE LABELED 12.8.2 00130404 * H AND X DESCRIPTORS ARE NEVER REPEATED 13.1.1 00140404 * * FIELD WIDTH IS NEVER ZERO 13.5.11 00150404 * IF AN I/O LIST SPECIFIES AT LEAST ONE LIST ITEM 13.3 00160404 * AT LEAST ONE REPEATABLE EDIT DESCRIPTOR MUST EXIST 00170404 IN THE FORMAT SPECIFICATION. 00180404 * * ITEMS IN I/O LIST CORRESPOND TO FORMAT DESCRIPTORS 13.3 00190404 00200404 BB *** BBCCOMNT ******00210404 00220404 1978 FORTRAN COMPILER VALIDATION SYSTEM 00230404 VERSION 2.1 00240404 00250404 00260404 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00270404 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00280404 SOFTWARE STANDARDS VALIDATION GROUP 00290404 BUILDING 225 RM A266 00300404 GAITHERSBURG, MD 20899 00310404 00320404 00330404 00340404 BE *** BBCCOMNT ******00350404 00360404 INPUT DATA TO THIS SEG. CONSISTS OF 6 DATA CARD IMAGES IN COLS. 1 - 5500370404 OL. 1--------------------------------------------47 00380404 ARD 1 QRSTMNOPIJKLYZ127890ABCD3456EFGHUVWX/(),.' =+- 00390404 ARD 2 AABABCABCDABCDEABCDEFWXYZWXYZWXYZWXYZWXYZWXYZ 00400404 ARD 3 112123123412345123456 00410404 ARD 4 GGGGHHHHIIIIJJJJ 00420404 ARD 5 ----LLLL 00430404 ARD 6 ....NNNN 00440404 * 00450404 S P E C I F I C A T I O N S SEGMENT 022 00460404 * 00470404 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00700404 FOR IDENTIFYING THE TEST ENVIRONMENT 00710404 00720404 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00730404 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00740404 Z03 ZPROG = 'PROGRAM NAME' 00750404 Z04 ZDATE = 'DATE OF TEST' 00760404 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00770404 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00780404 Z07 ZNAME = 'NAME OF USER' 00790404 Z08 ZTAPE = 'TAPE OWNER/ID' 00800404 Z09 ZTAPED = 'DATE TAPE COPIED' 00810404 00820404 01120404 WRITE REPORT TITLE 01130404 01140404 01220404 * HEADER FOR SEGMENT 22 01230404 WRITE DETAIL REPORT HEADERS 01290404 01300404 01370404 * TESTS THAT ALL FORTRAN (SUBSET) CHARACTERS MAY BE READ. 3.101380404 01390404 * INPUT CARD 1 01400404 01610404 * AW CONVERSION IS USED IN THE FORMAT STATEMENTS. 3.5.1101620404 SOME FORMAT DESCRIPTORS ARE REPEATED. 01630404 * THE FOLLOWING THREE CASES ARE USED FOR BOTH INPUT AND OUTPUT. 01640404 INPUT FIELD WIDTH = CHARACTER VARIABLE LENGTH 01650404 * INPUT FIELD WIDTH < CHARACTER VARIABLE LENGTH 01660404 INPUT FIELD WIDTH > CHARACTER VARIABLE LENGTH 01670404 * 01680404 INPUT CARD 2 01690404 * 01860404 T003 TEST 3 01870404 02000404 * A CONVERSION IS USED IN THE FORMAT STATEMENTS. 3.5.1102010404 SOME FORMAT DESCRIPTORS ARE REPEATED. 02020404 * READ WITH A-EDIT DESCRIPTOR, A STRING, FOLLOWED BY ANOTHER 02030404 FIELD TO SHOW THAT THE POINTER PICKS UP THE NEXT FIELD 02040404 * FOLLOWING THE COUNT OF THE LENGTH OF THE DECLARED VARIABLE. 02050404 02060404 * INPUT CARD 3 02070404 02200404 * TEST THAT A SLASH ON INPUT CAUSES THE UNPROCESSED CHARACTERS 02210404 TO BE SKIPPED. 13.5.402220404 * ALSO TEST THAT AN APOSTROPHE MAY BE USED INSTEAD OF AN 13.5.102230404 H-EDIT DESCRIPTOR. 13.5.202240404 * 02250404 INPUT CARD 4 02260404 * INPUT CARDS 5-6 02290404 02450404 BB *** BBCSUM0 ******02460404 WRITE OUT TEST SUMMARY 02470404 02480404 WRITE OUT REPORT FOOTINGS 02600404 02610404 FORMATS FOR TEST DETAIL LINES 02670404 02680404 FORMAT STATEMENTS FOR PAGE HEADERS 02880404 02890404 03020404 FORMAT STATEMENTS FOR REPORT FOOTINGS 03030404 03040404 03090404 FORMAT STATEMENTS FOR RUN SUMMARY 03100404 03110404 * 03180404 ** END OF TEST SEGMENT 022 03190404
Calls
Contents
Variables
A1VK A2VK A3VK A41K A43K A4VK A5VK A6VK REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
character(len=1) :: A1VK
character(len=2) :: A2VK
character(len=3) :: A3VK
character(len=4) :: A41K(6)
character(len=4) :: A43K(2,2,3)
character(len=4) :: A4VK
character(len=5) :: A5VK
character(len=6) :: A6VK
* 00540404 BB* **** BBCINITA *****00550404 SPECIFICATION STATEMENTS 00560404 *** 00570404
character :: REMRKS*31
*** INITIALIZE SECTION 00620404
character :: ZCOMPL*20
*** INITIALIZE SECTION 00620404
character :: ZDATE*17
*** INITIALIZE SECTION 00620404
character :: ZNAME*20
*** INITIALIZE SECTION 00620404
character :: ZPROG*5
*** INITIALIZE SECTION 00620404
character :: ZPROJ*13
*** INITIALIZE SECTION 00620404
character :: ZTAPE*10
*** INITIALIZE SECTION 00620404
character :: ZTAPED*13
*** INITIALIZE SECTION 00620404
character :: ZVERS*13
*** INITIALIZE SECTION 00620404
character :: ZVERSD*17
*** INITIALIZE SECTION 00620404
Call graph
fm404 calls 1, 3, 4