FM500 – NIST-Fortran78
FM500 Program
5 statements
Source File
**********00010500 * FORTRAN 77 00020500 FM500 00030500 * BLKD1 - (260) 00040500 THIS PROGRAM USES SN501 AND AN502 00050500 **********00060500 * TESTING OF BLOCK DATA SUBPROGRAMS FEATURES ANS REF 00070500 IMPLICIT, PARAMETER, EXTERNAL, AND SAVE 16 00080500 * THIS SEGMENT USES BLOCK DATA PROGRAM 00090500 AN502 AND SUBROUTINE SN501 00100500 * 00110500 S P E C I F I C A T I O N S SEGMENT 260 00120500 * DECLARATION OF VARIABLES IN COMMON BLOCKS 00140500 PARAMETER (KPI = 2, LPI = 10) 00150500 * INTEGER FXVI 00160500 REAL JX1S 00170500 * DOUBLE PRECISION AX1D, BX4D 00180500 DIMENSION BX4D(KPI, KPI, KPI, KPI) 00190500 * COMPLEX AXVC, BX1C, CZ5C 00200500 LOGICAL AXVB, BZ1B, CX6B(2,2,2,2,2,2) 00210500 * CHARACTER1 A1XVK, B1X1K, C1X7K 00220500 CHARACTER*2 D2Z1K 00230500 * CHARACTER4 E4XVK, G4X2K 00240500 CHARACTER(LPI) I10XVK 00250500 * 00260500 COMMON /BLK1/ IXVI, FXVI, KX1I(2), HX2I(2,2), MX2I(2,2) 00270500 * COMMON /BLK2/ AXVS, BXVS, JX1S(2), CX2S(2,2), DZ3S(2,2,2), EZVS 00280500 COMMON /BLK3/ RXVD, AX1D(2), BX4D 00290500 * COMMON /BLK4/ AXVC, BX1C(2), CZ5C(2,2,2,2,2) 00300500 COMMON /BLK5/ AXVB, BZ1B(2), CX6B 00310500 * COMMON /BLK6/ A1XVK, B1X1K(2), C1X7K(2,2,2,2,2,2,2), 00320500 S2XVK, D2Z1K(2), E4XVK, G4X2K(2,2), I10XVK 00330500 * 00340500 * END OF TEST SEGMENT 260 00370500
Calls
Contents
None
Call graph
fm500 calls sn501
sn501 calls mx2i, kx1i, dz3s, 2, cx2s, hx2i