FM517 – NIST-Fortran78
FM517 Program
182 statements
Source File
00130517 1978 FORTRAN COMPILER VALIDATION SYSTEM 00140517 VERSION 2.1 00150517 00160517 00170517 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00180517 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00190517 SOFTWARE STANDARDS VALIDATION GROUP 00200517 BUILDING 225 RM A266 00210517 GAITHERSBURG, MD 20899 00220517 00230517 00240517 00250517 BE* **** BBCCOMNT *****00260517 SPECIFICATION STATEMENTS 00300517 00310517 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00480517 FOR IDENTIFYING THE TEST ENVIRONMENT 00490517 00500517 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00510517 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00520517 Z03 ZPROG = 'PROGRAM NAME' 00530517 Z04 ZDATE = 'DATE OF TEST' 00540517 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00550517 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00560517 Z07 ZNAME = 'NAME OF USER' 00570517 Z08 ZTAPE = 'TAPE OWNER/ID' 00580517 Z09 ZTAPED = 'DATE TAPE COPIED' 00590517 00600517 00880517 WRITE REPORT TITLE 00890517 00900517 WRITE DETAIL REPORT HEADERS 00990517 01000517 WRITE OUT TEST SUMMARY 02280517 02290517 WRITE OUT REPORT FOOTINGS 02410517 02420517 FORMATS FOR TEST DETAIL LINES 02500517 02510517 FORMATS FOR TEST DETAIL LINES - FULL LANGUAGE 02710517 02720517 FORMAT STATEMENTS FOR PAGE HEADERS 02860517 02870517 03000517 FORMAT STATEMENTS FOR REPORT FOOTINGS 03010517 03020517 03070517 FORMAT STATEMENTS FOR RUN SUMMARY 03080517 *** 03090517
Calls
Contents
Variables
REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
character :: REMRKS*31
*** INITIALIZE SECTION 00400517
character :: ZCOMPL*20
*** INITIALIZE SECTION 00400517
character :: ZDATE*17
*** INITIALIZE SECTION 00400517
character :: ZNAME*20
*** INITIALIZE SECTION 00400517
character :: ZPROG*5
*** INITIALIZE SECTION 00400517
character :: ZPROJ*13
*** INITIALIZE SECTION 00400517
character :: ZTAPE*10
*** INITIALIZE SECTION 00400517
character :: ZTAPED*13
*** INITIALIZE SECTION 00400517
character :: ZVERS*13
*** INITIALIZE SECTION 00400517
character :: ZVERSD*17
*** INITIALIZE SECTION 00400517
Call graph
fm517 calls 27, en872, sn519, sn518