FM710 – NIST-Fortran78
FM710 Program
331 statements
Source File
00110710 1978 FORTRAN COMPILER VALIDATION SYSTEM 00120710 VERSION 2.1 00130710 00140710 00150710 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00160710 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00170710 SOFTWARE STANDARDS VALIDATION GROUP 00180710 BUILDING 225 RM A266 00190710 GAITHERSBURG, MD 20899 00200710 00210710 00220710 00230710 BE* **** BBCCOMNT *****00240710 SPECIFICATION STATEMENTS 00280710 00290710 INITIALIZE SECTION 00480710 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00560710 FOR IDENTIFYING THE TEST ENVIRONMENT 00570710 00580710 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00590710 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00600710 Z03 ZPROG = 'PROGRAM NAME' 00610710 Z04 ZDATE = 'DATE OF TEST' 00620710 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00630710 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00640710 Z07 ZNAME = 'NAME OF USER' 00650710 Z08 ZTAPE = 'TAPE OWNER/ID' 00660710 Z09 ZTAPED = 'DATE TAPE COPIED' 00670710 00680710 00960710 WRITE REPORT TITLE 00970710 00980710 WRITE DETAIL REPORT HEADERS 01070710 01080710 WRITE OUT TEST SUMMARY 04650710 04660710 WRITE OUT REPORT FOOTINGS 04780710 04790710 FORMATS FOR TEST DETAIL LINES 04870710 04880710 FORMATS FOR TEST DETAIL LINES - FULL LANGUAGE 05080710 05090710 FORMAT STATEMENTS FOR PAGE HEADERS 05230710 05240710 05370710 FORMAT STATEMENTS FOR REPORT FOOTINGS 05380710 05390710 05440710 FORMAT STATEMENTS FOR RUN SUMMARY 05450710 05460710
Calls
Contents
Variables
C2N001 CVCOMP CVCORR CVN001 REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
character(len=10) :: C2N001(2,4)
character(len=10) :: CVCOMP
character(len=10) :: CVCORR
character(len=10) :: CVN001
character :: REMRKS*31
character :: ZCOMPL*20
character :: ZDATE*17
character :: ZNAME*20
character :: ZPROG*5
character :: ZPROJ*13
character :: ZTAPE*10
character :: ZTAPED*13
character :: ZVERS*13
character :: ZVERSD*17
Call graph
fm710 calls i2n001, 27, i2n002, i1n003, i2n004