FM719 – NIST-Fortran78
FM719 Program
310 statements
Source File
00120719 1978 FORTRAN COMPILER VALIDATION SYSTEM 00130719 VERSION 2.1 00140719 00150719 00160719 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00170719 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00180719 SOFTWARE STANDARDS VALIDATION GROUP 00190719 BUILDING 225 RM A266 00200719 GAITHERSBURG, MD 20899 00210719 00220719 00230719 00240719 BE* **** BBCCOMNT *****00250719 SPECIFICATION STATEMENTS 00290719 00300719 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00470719 FOR IDENTIFYING THE TEST ENVIRONMENT 00480719 00490719 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00500719 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00510719 Z03 ZPROG = 'PROGRAM NAME' 00520719 Z04 ZDATE = 'DATE OF TEST' 00530719 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00540719 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00550719 Z07 ZNAME = 'NAME OF USER' 00560719 Z08 ZTAPE = 'TAPE OWNER/ID' 00570719 Z09 ZTAPED = 'DATE TAPE COPIED' 00580719 00590719 00870719 WRITE REPORT TITLE 00880719 00890719 WRITE DETAIL REPORT HEADERS 00980719 00990719 WRITE OUT TEST SUMMARY 03940719 03950719 WRITE OUT REPORT FOOTINGS 04070719 04080719 FORMATS FOR TEST DETAIL LINES 04160719 04170719 FORMATS FOR TEST DETAIL LINES - FULL LANGUAGE 04370719 04380719 FORMAT STATEMENTS FOR PAGE HEADERS 04520719 04530719 04660719 FORMAT STATEMENTS FOR REPORT FOOTINGS 04670719 04680719 04730719 FORMAT STATEMENTS FOR RUN SUMMARY 04740719 *** 04750719
Calls
Contents
Variables
DVCOMP DVCORR DVN001 REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
double precision :: DVCOMP
*** INITIALIZE SECTION 00390719
double precision :: DVCORR
*** INITIALIZE SECTION 00390719
double precision :: DVN001
*** INITIALIZE SECTION 00390719
character :: REMRKS*31
character :: ZCOMPL*20
character :: ZDATE*17
character :: ZNAME*20
character :: ZPROG*5
character :: ZPROJ*13
character :: ZTAPE*10
character :: ZTAPED*13
character :: ZVERS*13
character :: ZVERSD*17
Call graph
fm719 calls 27, if720, sn721, en721, en722