FM801 – NIST-Fortran78
FM801 Program
623 statements
Source File
**********00010801 * FORTRAN 77 00020801 FM801 YDINT - (155) 00030801 * 00040801 **********00050801 GENERAL PURPOSE ANS REF 00060801 * TEST INTRINSIC FUNCTIONS DINT, DNINT, IDNINT 15.3 00070801 TRUNCATION (SIGN OF A * LARGEST INTEGER LE ABS(A)) (TABLE 5)00080801 * 00090801 GENERAL COMMENTS 00100801 * FLOAT FUNCTION ASSUMED WORKING 00110801 00120801 BB *** BBCCOMNT ******00130801 00140801 1978 FORTRAN COMPILER VALIDATION SYSTEM 00150801 VERSION 2.1 00160801 00170801 00180801 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00190801 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00200801 SOFTWARE STANDARDS VALIDATION GROUP 00210801 BUILDING 225 RM A266 00220801 GAITHERSBURG, MD 20899 00230801 00240801 00250801 00260801 BE *** BBCCOMNT ******00270801 00280801 * S P E C I F I C A T I O N S SEGMENT 155 00290801 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00470801 FOR IDENTIFYING THE TEST ENVIRONMENT 00480801 00490801 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00500801 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00510801 Z03 ZPROG = 'PROGRAM NAME' 00520801 Z04 ZDATE = 'DATE OF TEST' 00530801 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00540801 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00550801 Z07 ZNAME = 'NAME OF USER' 00560801 Z08 ZTAPE = 'TAPE OWNER/ID' 00570801 Z09 ZTAPED = 'DATE TAPE COPIED' 00580801 00590801 00880801 WRITE REPORT TITLE 00890801 00900801 00980801 * HEADER FOR SEGMENT 155 00990801 WRITE DETAIL REPORT HEADERS 01050801 01060801 01130801 * TEST OF DINT 01140801 01150801 * 02610801 02650801 * TEST OF DNINT 02660801 02670801 * 04920801 04960801 * TEST OF IDNINT 04970801 04980801 * 04990801 07070801 BB *** BBCSUM0 ******07080801 WRITE OUT TEST SUMMARY 07090801 07100801 WRITE OUT REPORT FOOTINGS 07220801 07230801 FORMATS FOR TEST DETAIL LINES 07290801 07300801 FORMATS FOR TEST DETAIL LINES - FULL LANGUAGE 07500801 07510801 FORMAT STATEMENTS FOR PAGE HEADERS 07650801 07660801 07790801 FORMAT STATEMENTS FOR REPORT FOOTINGS 07800801 07810801 07860801 FORMAT STATEMENTS FOR RUN SUMMARY 07870801 07880801 07950801 *** END OF TEST SEGMENT 155 07960801
Calls
Contents
Variables
DNAVD DNBVD DNDVD REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
double precision :: DNAVD
* 00310801 BB* **** BBCINITA *****00320801 SPECIFICATION STATEMENTS 00330801 *** 00340801
double precision :: DNBVD
* 00310801 BB* **** BBCINITA *****00320801 SPECIFICATION STATEMENTS 00330801 *** 00340801
double precision :: DNDVD
* 00310801 BB* **** BBCINITA *****00320801 SPECIFICATION STATEMENTS 00330801 *** 00340801
character :: REMRKS*31
*** INITIALIZE SECTION 00390801
character :: ZCOMPL*20
*** INITIALIZE SECTION 00390801
character :: ZDATE*17
*** INITIALIZE SECTION 00390801
character :: ZNAME*20
*** INITIALIZE SECTION 00390801
character :: ZPROG*5
*** INITIALIZE SECTION 00390801
character :: ZPROJ*13
*** INITIALIZE SECTION 00390801
character :: ZTAPE*10
*** INITIALIZE SECTION 00390801
character :: ZTAPED*13
*** INITIALIZE SECTION 00390801
character :: ZVERS*13
*** INITIALIZE SECTION 00390801
character :: ZVERSD*17
*** INITIALIZE SECTION 00390801
Call graph
fm801 calls dnint, idnint, float, dint