FM810 – NIST-Fortran78
FM810 Program
219 statements
Source File
**********00010810 * FORTRAN 77 00020810 FM810 YDMMX - (173) 00030810 * 00040810 **********00050810 GENERAL PURPOSE ANS REF 00060810 * TESTS THE USE OF INTEGER, REAL, DOUBLE PRECISION, 15.3 00070810 AND MIXED MODE EXPRESSIONS CONTAINING REFERENCES TO 15.10 00080810 * THE INTRINSIC FUNCTIONS OF THE FULL LANGUAGE 6.1.4 00090810 00100810 * GENERAL COMMENTS 00110810 SEGMENTS TESTING XINT, XREAL, XAINT, XABS, XAMOD, 00120810 * XSIGN, XDIM, XMAX, XMIN, YIDINT, YSNGL 00130810 YDINT, YDABS, YCABS, YDMOD, YDSIGN, 00140810 * YDMAX1, YDMIN1, YDBLE, YCONJG ASSUMED WORKING 00150810 BB* **** BBCCOMNT *****00160810 00170810 1978 FORTRAN COMPILER VALIDATION SYSTEM 00180810 VERSION 2.1 00190810 00200810 00210810 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00220810 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00230810 SOFTWARE STANDARDS VALIDATION GROUP 00240810 BUILDING 225 RM A266 00250810 GAITHERSBURG, MD 20899 00260810 00270810 00280810 00290810 BE **** BBCCOMNT ******00300810 00310810 * S P E C I F I C A T I O N S SEGMENT 173 00320810 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00490810 FOR IDENTIFYING THE TEST ENVIRONMENT 00500810 00510810 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00520810 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00530810 Z03 ZPROG = 'PROGRAM NAME' 00540810 Z04 ZDATE = 'DATE OF TEST' 00550810 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00560810 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00570810 Z07 ZNAME = 'NAME OF USER' 00580810 Z08 ZTAPE = 'TAPE OWNER/ID' 00590810 Z09 ZTAPED = 'DATE TAPE COPIED' 00600810 00610810 00900810 WRITE REPORT TITLE 00910810 00920810 01000810 * 01010810 HEADER FOR SEGMENT 173 WRITTEN 01020810 WRITE DETAIL REPORT HEADERS 01090810 01100810 * 01170810 T001 TEST 1 01180810 02640810 BB *** BBCSUM0 ******02650810 WRITE OUT TEST SUMMARY 02660810 02670810 WRITE OUT REPORT FOOTINGS 02790810 02800810 FORMATS FOR TEST DETAIL LINES 02860810 02870810 FORMATS FOR TEST DETAIL LINES - FULL LANGUAGE 03070810 03080810 FORMAT STATEMENTS FOR PAGE HEADERS 03220810 03230810 03360810 FORMAT STATEMENTS FOR REPORT FOOTINGS 03370810 03380810 03430810 FORMAT STATEMENTS FOR RUN SUMMARY 03440810 03450810 * END OF TEST SEGMENT 173 03520810
Calls
Contents
Variables
DVCORR DXAVD DXBVD DXDVD DXEVD DXFVD DXGVD REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
double precision :: DVCORR
SPECIFICATION STATEMENTS 00350810 00360810
double precision :: DXAVD
SPECIFICATION STATEMENTS 00350810 00360810
double precision :: DXBVD
SPECIFICATION STATEMENTS 00350810 00360810
double precision :: DXDVD
SPECIFICATION STATEMENTS 00350810 00360810
double precision :: DXEVD
SPECIFICATION STATEMENTS 00350810 00360810
double precision :: DXFVD
SPECIFICATION STATEMENTS 00350810 00360810
double precision :: DXGVD
SPECIFICATION STATEMENTS 00350810 00360810
character :: REMRKS*31
*** INITIALIZE SECTION 00410810
character :: ZCOMPL*20
*** INITIALIZE SECTION 00410810
character :: ZDATE*17
*** INITIALIZE SECTION 00410810
character :: ZNAME*20
*** INITIALIZE SECTION 00410810
character :: ZPROG*5
*** INITIALIZE SECTION 00410810
character :: ZPROJ*13
*** INITIALIZE SECTION 00410810
character :: ZTAPE*10
*** INITIALIZE SECTION 00410810
character :: ZTAPED*13
*** INITIALIZE SECTION 00410810
character :: ZVERS*13
*** INITIALIZE SECTION 00410810
character :: ZVERSD*17
*** INITIALIZE SECTION 00410810
Call graph
fm810 calls dmod, idint, sngl, dint, dnint, dsign, ddim