FM811 – NIST-Fortran78
FM811 Program
227 statements
Source File
**********00010811 * FORTRAN 77 00020811 FM811 YCMMX - (174) 00030811 * 00040811 **********00050811 GENERAL PURPOSE ANS REF 00060811 * TESTS THE USE OF INTEGER, REAL, DOUBLE PRECISION, 15.10 00070811 AND COMPLEX EXPRESSIONS CONTAINING REFERENCE (TABLE 5)00080811 * TO THE INTRINSIC FUNCTIONS OF THE FULL LANGUAGE 6.1.4 00090811 00100811 * GENERAL COMMENTS 00110811 SEGMENTS TESTING XINT, XREAL, XAINT, XABS, XAMOD, 00120811 * XSIGN, XDIM, XMAX, XMIN, YIDINT, YSNGL 00130811 YDINT, YDABS, YCABS, YDMOD, YDSIGN, 00140811 * YDMAX1, YDMIN1, YDBLE, YCONJG ASSUMED WORKING 00150811 00160811 BB *** BBCCOMNT ******00170811 00180811 1978 FORTRAN COMPILER VALIDATION SYSTEM 00190811 VERSION 2.1 00200811 00210811 00220811 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00230811 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00240811 SOFTWARE STANDARDS VALIDATION GROUP 00250811 BUILDING 225 RM A266 00260811 GAITHERSBURG, MD 20899 00270811 00280811 00290811 00300811 BE *** BBCCOMNT ******00310811 00320811 * S P E C I F I C A T I O N S SEGMENT 174 00330811 * 00380811 BB *** BBCINITA ******00390811 SPECIFICATION STATEMENTS 00400811 00410811 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00540811 FOR IDENTIFYING THE TEST ENVIRONMENT 00550811 00560811 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00570811 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00580811 Z03 ZPROG = 'PROGRAM NAME' 00590811 Z04 ZDATE = 'DATE OF TEST' 00600811 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00610811 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00620811 Z07 ZNAME = 'NAME OF USER' 00630811 Z08 ZTAPE = 'TAPE OWNER/ID' 00640811 Z09 ZTAPED = 'DATE TAPE COPIED' 00650811 00660811 00950811 WRITE REPORT TITLE 00960811 00970811 01050811 * HEADER FOR SEGMENT 174 WRITTEN 01060811 WRITE DETAIL REPORT HEADERS 01130811 01140811 01210811 T001 TEST 1 IDINT 01220811 * 02720811 BB* **** BBCSUM0 *****02730811 WRITE OUT TEST SUMMARY 02740811 02750811 WRITE OUT REPORT FOOTINGS 02870811 02880811 FORMATS FOR TEST DETAIL LINES 02940811 02950811 FORMATS FOR TEST DETAIL LINES - FULL LANGUAGE 03150811 03160811 FORMAT STATEMENTS FOR PAGE HEADERS 03300811 03310811 03440811 FORMAT STATEMENTS FOR REPORT FOOTINGS 03450811 03460811 03510811 FORMAT STATEMENTS FOR RUN SUMMARY 03520811 03530811 03600811 **** END OF TEST SEGMENT 174 03610811
Calls
Contents
Variables
CYAVC CYDVC DVCORR DYAVD DYBVD DYDVD R2E REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVCORR ZVERS ZVERSD
Variables
Type Attributes Name Initial
complex :: CYAVC
complex :: CYDVC
double precision :: DVCORR
double precision :: DYAVD
double precision :: DYBVD
double precision :: DYDVD
real :: R2E(2)
character :: REMRKS*31
*** INITIALIZE SECTION 00460811
character :: ZCOMPL*20
*** INITIALIZE SECTION 00460811
character :: ZDATE*17
*** INITIALIZE SECTION 00460811
character :: ZNAME*20
*** INITIALIZE SECTION 00460811
character :: ZPROG*5
*** INITIALIZE SECTION 00460811
character :: ZPROJ*13
*** INITIALIZE SECTION 00460811
character :: ZTAPE*10
*** INITIALIZE SECTION 00460811
character :: ZTAPED*13
*** INITIALIZE SECTION 00460811
complex :: ZVCORR
character :: ZVERS*13
*** INITIALIZE SECTION 00460811
character :: ZVERSD*17
*** INITIALIZE SECTION 00460811
Call graph
fm811 calls amin0, dmod, idint, idnint, sngl, dint, dnint, dsign, ddim, amax1