FM833 – NIST-Fortran78
FM833 Program
231 statements
Source File
**********00010833 * FORTRAN 77 00020833 FM833 00030833 * YGEN6 - (211) 00040833 00050833 **********00060833 * GENERAL PURPOSE ANS REF 00070833 TEST GENERIC FUNCTIONS 15.3 00080833 * SPECIFIC AND GENERIC NAME OF SAME FUNCTION WITH TABLE 5 00090833 SAME TYPE OF ARGUMENT IN A STATEMENT 00100833 * 00110833 BB* **** BBCCOMNT *****00120833 00130833 1978 FORTRAN COMPILER VALIDATION SYSTEM 00140833 VERSION 2.1 00150833 00160833 00170833 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00180833 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00190833 SOFTWARE STANDARDS VALIDATION GROUP 00200833 BUILDING 225 RM A266 00210833 GAITHERSBURG, MD 20899 00220833 00230833 00240833 00250833 BE **** BBCCOMNT ******00260833 00270833 * S P E C I F I C A T I O N S SEGMENT 211 00280833 00330833 BB *** BBCINITA ******00340833 SPECIFICATION STATEMENTS 00350833 00360833 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00490833 FOR IDENTIFYING THE TEST ENVIRONMENT 00500833 00510833 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00520833 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00530833 Z03 ZPROG = 'PROGRAM NAME' 00540833 Z04 ZDATE = 'DATE OF TEST' 00550833 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00560833 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00570833 Z07 ZNAME = 'NAME OF USER' 00580833 Z08 ZTAPE = 'TAPE OWNER/ID' 00590833 Z09 ZTAPED = 'DATE TAPE COPIED' 00600833 00610833 00900833 WRITE REPORT TITLE 00910833 00920833 01000833 * HEADER FOR SEGMENT 211 01010833 WRITE DETAIL REPORT HEADERS 01070833 01080833 01150833 T001 TEST 1 TEST OF ISIGN AND SIGN WITH INTEGER 01160833 * 02690833 BB* **** BBCSUM0 *****02700833 WRITE OUT TEST SUMMARY 02710833 02720833 WRITE OUT REPORT FOOTINGS 02840833 02850833 FORMATS FOR TEST DETAIL LINES 02910833 02920833 FORMATS FOR TEST DETAIL LINES - FULL LANGUAGE 03120833 03130833 FORMAT STATEMENTS FOR PAGE HEADERS 03270833 03280833 03410833 FORMAT STATEMENTS FOR REPORT FOOTINGS 03420833 03430833 03480833 FORMAT STATEMENTS FOR RUN SUMMARY 03490833 03500833 03570833 * END OF TEST SEGMENT 211 03580833
Calls
Contents
Variables
AVC AVD BVC BVD CVD DVCORR R2E REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVCORR ZVERS ZVERSD
Variables
Type Attributes Name Initial
complex :: AVC
double precision :: AVD
complex :: BVC
double precision :: BVD
double precision :: CVD
double precision :: DVCORR
real :: R2E(2)
character :: REMRKS*31
*** INITIALIZE SECTION 00410833
character :: ZCOMPL*20
*** INITIALIZE SECTION 00410833
character :: ZDATE*17
*** INITIALIZE SECTION 00410833
character :: ZNAME*20
*** INITIALIZE SECTION 00410833
character :: ZPROG*5
*** INITIALIZE SECTION 00410833
character :: ZPROJ*13
*** INITIALIZE SECTION 00410833
character :: ZTAPE*10
*** INITIALIZE SECTION 00410833
character :: ZTAPED*13
*** INITIALIZE SECTION 00410833
complex :: ZVCORR
character :: ZVERS*13
*** INITIALIZE SECTION 00410833
character :: ZVERSD*17
*** INITIALIZE SECTION 00410833
Call graph
fm833 calls clog, dmod, dtanh, dasin, isign, dnint, amax1, csqrt, dexp, csin