FM910 – NIST-Fortran78
FM910 Program
241 statements
Source File
**********00010910 * FM910 00020910 DIRAF2 - (411) 00030910 * THIS PROGRAM CALLS SUBROUTINE SN911 IN FILE FM911 00040910 **********00050910 TESTING OF DIRECT ACCESS FILES ANS REF 00060910 * UNFORMATTED WITH BOTH SEQUENTIAL AND DIRECT 12.5 00070910 ACCESS TO THE SAME FILE 00080910 * NAMED FILE AND SCRATCH FILE 00090910 00100910 * USES SUBROUTINE SN911 00110910 00120910 BB *** BBCCOMNT ******00130910 00140910 1978 FORTRAN COMPILER VALIDATION SYSTEM 00150910 VERSION 2.1 00160910 00170910 00180910 SUGGESTIONS AND COMMENTS SHOULD BE FORWARDED TO 00190910 NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY 00200910 SOFTWARE STANDARDS VALIDATION GROUP 00210910 BUILDING 225 RM A266 00220910 GAITHERSBURG, MD 20899 00230910 00240910 00250910 00260910 BE *** BBCCOMNT ******00270910 00280910 * S P E C I F I C A T I O N S SEGMENT 910 00290910 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00560910 FOR IDENTIFYING THE TEST ENVIRONMENT 00570910 00580910 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00590910 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00600910 Z03 ZPROG = 'PROGRAM NAME' 00610910 Z04 ZDATE = 'DATE OF TEST' 00620910 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00630910 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00640910 Z07 ZNAME = 'NAME OF USER' 00650910 Z08 ZTAPE = 'TAPE OWNER/ID' 00660910 Z09 ZTAPED = 'DATE TAPE COPIED' 00670910 00680910 * 00930910 THE FOLLOWING STATEMENT MUST BE CHANGED IF THE 00940910 * UNITS GIVEN ARE NOT CAPABLE OF BEING OPENED AS SPECIFIED. 00950910 00960910 I10 CONTAINS THE UNIT NUMBER FOR A NAMED DIRECT ACCESS FILE. 00970910 * 01010910 I11 CONTAINS THE UNIT NUMBER FOR A SCRATCH DIRECT ACCESS FILE. 01020910 01060910 * THE FOLLOWING STATEMENT MUST BE CHANGED IF THE NAME 01070910 GIVEN IS NOT A VALID FILE SPECIFIER FOR A DIRECT, 01080910 * UNFORMATTED FILE. 01090910 01100910 CDIR CONTAINS THE FILE NAME FOR UNIT I10. 01110910 * FILE NUMBER AND NAME ASSIGNMENT 01170910 01240910 WRITE REPORT TITLE 01250910 01260910 * 01340910 HEADER FOR SEGMENT 910 01350910 WRITE DETAIL REPORT HEADERS 01410910 01420910 * INITIALIZE DATA 01490910 01520910 * WRITE DIRECT FILE IN SEQUENTIAL ORDER 01550910 CHECK TO SEE IF IT CAN BE OPEN SEQUENTIAL 01640910 * 02100910 AND READ IN SEQUENTIAL ORDER 02130910 * 02160910 02420910 * FILE IN NONSEQUENTIAL ORDER 02450910 02480910 * 02750910 02770910 T004 TEST 4 CHECK RECL AND NEXTREC ON SCRATCH FILE 02780910 * 02930910 WRITE DIRECT ACCESS 02940910 * SCRATCH FILE IN NONSEQUENTIAL ORDER 02950910 * BY READING IT IN NONSEQUENTIAL ORDER 03060910 * 03340910 T006 TEST 6 CHECK RECL AND NEXTREC AFTER READING 03350910 03500910 * 03520910 04070910 BB *** BBCSUM0 ******04080910 WRITE OUT TEST SUMMARY 04090910 04100910 WRITE OUT REPORT FOOTINGS 04220910 04230910 FORMATS FOR TEST DETAIL LINES 04290910 04300910 FORMATS FOR TEST DETAIL LINES - FULL LANGUAGE 04500910 04510910 FORMAT STATEMENTS FOR PAGE HEADERS 04650910 04660910 04790910 FORMAT STATEMENTS FOR REPORT FOOTINGS 04800910 04810910 04860910 FORMAT STATEMENTS FOR RUN SUMMARY 04870910 04880910 * 04950910 ** END OF TEST SEGMENT 910 04960910
Calls
Contents
Variables
A41K A4VK AVB AVC AVD B1D B4VK BVB BVC BVD C1B C1C C41K CDIR D1C D1D D4VK E1B REMRKS ZCOMPL ZDATE ZNAME ZPROG ZPROJ ZTAPE ZTAPED ZVERS ZVERSD
Variables
Type Attributes Name Initial
character(len=4) :: A41K(10)
character(len=4) :: A4VK
logical :: AVB
complex :: AVC
* 00350910 * BELOW CHARACTER STATEMENT ESTABLISHES THE FILE NAME VARIABLES. 00360910 X20 REPLACED BY FEXEC X-20 CONTROL CARD. X-20 IS FOR REPLACING 00370910
double precision :: AVD
double precision :: B1D(15)
character(len=4) :: B4VK
logical :: BVB
complex :: BVC
* 00350910 * BELOW CHARACTER STATEMENT ESTABLISHES THE FILE NAME VARIABLES. 00360910 X20 REPLACED BY FEXEC X-20 CONTROL CARD. X-20 IS FOR REPLACING 00370910
double precision :: BVD
logical :: C1B(10)
complex :: C1C(10)
* 00350910 * BELOW CHARACTER STATEMENT ESTABLISHES THE FILE NAME VARIABLES. 00360910 X20 REPLACED BY FEXEC X-20 CONTROL CARD. X-20 IS FOR REPLACING 00370910
character(len=4) :: C41K(15)
character(len=15) :: CDIR
SPECIFICATION STATEMENTS 00420910 00430910
complex :: D1C(15)
* 00350910 * BELOW CHARACTER STATEMENT ESTABLISHES THE FILE NAME VARIABLES. 00360910 X20 REPLACED BY FEXEC X-20 CONTROL CARD. X-20 IS FOR REPLACING 00370910
double precision :: D1D(10)
character(len=4) :: D4VK
logical :: E1B(15)
character :: REMRKS*31
*** INITIALIZE SECTION 00480910
character :: ZCOMPL*20
*** INITIALIZE SECTION 00480910
character :: ZDATE*17
*** INITIALIZE SECTION 00480910
character :: ZNAME*20
*** INITIALIZE SECTION 00480910
character :: ZPROG*5
*** INITIALIZE SECTION 00480910
character :: ZPROJ*13
*** INITIALIZE SECTION 00480910
character :: ZTAPE*10
*** INITIALIZE SECTION 00480910
character :: ZTAPED*13
*** INITIALIZE SECTION 00480910
character :: ZVERS*13
*** INITIALIZE SECTION 00480910
character :: ZVERSD*17
*** INITIALIZE SECTION 00480910
Call graph
fm910 calls f1s, sn911, n1i, l1i, h1s
sn911 calls nt1i, lt1i