wave2d – Refactored Shallow Water Simulator
wave2d Program
81 statements
Source File
Uses
module_update
sub
******! 2d shallow-water model ! ! including: ! - horizontal pressure-gradient force ! - shapiro filter ! - flooding algorithm ! ! author: j. kaempf, 2008 ! *****! ** debug
Calls
Contents
Variables
c dt dtmax dx dy eps eta etan g h hmax hmin hzero j k lambda n nout ntot nx ny time u un v vn wet
Source Code
wave2d
Variables
Type Attributes Name Initial
real :: c
real :: dt
real :: dtmax
real :: dx
real :: dy
real :: eps
real, dimension(0:ny+1,0:nx+1) :: eta
real, dimension(0:ny+1,0:nx+1) :: etan
real :: g
real, dimension(0:ny+1,0:nx+1) :: h
real :: hmax
real :: hmin
real, dimension(0:ny+1,0:nx+1) :: hzero
integer :: j
integer :: k
real :: lambda
integer :: n
integer :: nout
integer :: ntot
integer, parameter :: nx = 500
integer, parameter :: ny = 500
real :: time
real, dimension(0:ny+1,0:nx+1) :: u
real, dimension(0:ny+1,0:nx+1) :: un
real, dimension(0:ny+1,0:nx+1) :: v
real, dimension(0:ny+1,0:nx+1) :: vn
integer, dimension(0:ny+1,0:nx+1) :: wet
Source Code
      program wave2d
      use module_update
!*****************************************!
!* 2d shallow-water model                *!
!*                                       *!
!* including:                            *!
!* - horizontal pressure-gradient force  *!
!* - shapiro filter                      *!
!* - flooding algorithm                  *!
!*                                       *!
!* author: j. kaempf, 2008               *!
!*****************************************!
use sub
! local parameters
integer, parameter :: nx=500
integer, parameter :: ny=500
      real :: dt
      real :: dx
      real :: dy
      real :: eps
      real, dimension(0:ny+1,0:nx+1) :: eta
      real, dimension(0:ny+1,0:nx+1) :: etan
      real :: g
      real, dimension(0:ny+1,0:nx+1) :: h
      real :: hmin
      real, dimension(0:ny+1,0:nx+1) :: hzero
      integer :: j
      integer :: k
      real, dimension(0:ny+1,0:nx+1) :: u
      real, dimension(0:ny+1,0:nx+1) :: un
      real, dimension(0:ny+1,0:nx+1) :: v
      real, dimension(0:ny+1,0:nx+1) :: vn
      integer, dimension(0:ny+1,0:nx+1) :: wet
real :: hmax
real :: time
real :: dtmax
real :: c
real :: lambda
integer :: n
integer :: ntot
integer :: nout
! set local parameters
! runtime parameters
ntot = 10000
! set epsilon for Shapiro filter
eps = 0.05
call init(hmin,dx,dy,dt,g,j,k,hzero,eta,etan,h,wet,u,un,v,vn)
!**********
!debug
open(90,file ='debug.dat',form='formatted')
! output of initial eta distribution
open(10,file ='eta0.dat',form='formatted')
  do j = 0,ny+1
    write(10,'(101F12.6)')(eta(j,k),k=0,nx+1)
  end do
close(10)
! output of initial layer thickness distribution
open(10,file ='h0.dat',form='formatted')
  do j = 0,ny+1
    write(10,'(101F12.6)')(hzero(j,k),k=0,nx+1)
  end do
close(10)
! determine maximum water depth
hmax = 0.
do j = 1,ny
do k = 1,nx
  hmax = max(hmax,h(j,k))
end do
end do
! maximum phase speed
c = sqrt(2*g*hmax)
!
write(6,*)"c = ",c
! determine stability parameter
lambda = dt*sqrt(g*hmax)/min(dx,dy)
write(6,*)"lambda = ",lambda
if(lambda > 1)then
  write(6,*) "This will not work. Do you know why?"
  stop
end if
! open files for output
open(10,file ='eta.dat',form='formatted')
open(20,file ='h.dat',form='formatted')
open(30,file ='u.dat',form='formatted')
open(40,file ='v.dat',form='formatted')
do j = 26,26
do k = 26,26
eta(j,k) = 1.0
end do
end do
!---------------------------
! simulation loop
!---------------------------
do n = 1,ntot
time = real(n)*dt
! call predictor
  call dyn(j,k,eta,dt,dx,g,dy,un,u,wet,v,vn,h,etan)
! updating including Shapiro filter
  call shapiro(j,k,wet,etan,eps,eta)
      call update(dt,dx,dy,eps,eta,etan,g,h,hmin,hzero,j,k,u,un,v,vn,wet)
end do
!write results only once at the end....
do j = 0,ny+1
  write(10,'(101F12.6)')(eta(j,k),k=0,nx+1)
  write(20,'(101F12.6)')(h(j,k)  ,k=0,nx+1)
  write(30,'(101F12.6)')(u(j,k)  ,k=0,nx+1)
  write(40,'(101F12.6)')(v(j,k)  ,k=0,nx+1)
end do
write(6,*)"Data output at time = ",time/60.0," min"
end program wave2d
Call graph
wave2d calls update, dyn, shapiro, init
dyn calls dyn
shapiro calls shapiro
init calls init