FS303 – NIST-Fortran78
FS303 Subroutine
39 statements
Source File
subroutine FS303()
Arguments
None
Calls
Called by
Contents
Common Blocks
unnamed unnamed unnamed BLK1 BLK2 BLK2 BLK3 BLK4 BLK7 BLK8 BLKCHR
Common Blocks
common
Type Attributes Name Initial
integer :: IVCN01
common
Type Attributes Name Initial
real :: RVCN01//IVCN03
common
Type Attributes Name Initial
real :: //IACN11(4)
integer :: IVCN04
integer :: IVCN05
common /BLK1/
Type Attributes Name Initial
integer :: IVCNA1
common /BLK2/
Type Attributes Name Initial
integer :: IVCNB1
real :: RVCNB1
common /BLK2/
Type Attributes Name Initial
integer :: IVCNB2
common /BLK3/
Type Attributes Name Initial
integer :: IVCNC1
integer :: LVCNC1
common /BLK4/
Type Attributes Name Initial
integer :: IACN21(2,3)
real :: RACN11
common /BLK7/
Type Attributes Name Initial
integer :: IACN1G(5)
integer :: IVCNG1
common /BLK8/
Type Attributes Name Initial
integer :: IVCNH1
common /BLKCHR/
Type Attributes Name Initial
real :: CATN11
real :: CVTN01
real :: CVTN02
Call graph
fs303 calls racn11, iacn21, iacn1g
fm302 calls fs303