SN501 – NIST-Fortran78
SN501 Subroutine
527 statements
Source File
subroutine SN501()
* 00290501 DECLARATION OF VARIABLES IN COMMON BLOCKS 00330501 * 00550501 LOCAL DECLARATIONS 00570501 THE FOLLOWING 9 COMMENT LINES (CZ01, CZ02, ...) CAN BE REPLACED 00760501 FOR IDENTIFYING THE TEST ENVIRONMENT 00770501 00780501 Z01 ZVERS = 'VERSION OF THE COMPILER VALIDATION SYSTEM' 00790501 Z02 ZVERSD = 'CREATION DATE/TIME OF THE COMPILER VALIDATION SYSTEM' 00800501 Z03 ZPROG = 'PROGRAM NAME' 00810501 Z04 ZDATE = 'DATE OF TEST' 00820501 Z05 ZCOMPL = 'COMPILER IDENTIFICATION' 00830501 Z06 ZPROJ = 'PROJECT NUMBER/IDENTIFICATION' 00840501 Z07 ZNAME = 'NAME OF USER' 00850501 Z08 ZTAPE = 'TAPE OWNER/ID' 00860501 Z09 ZTAPED = 'DATE TAPE COPIED' 00870501 00880501 01170501 WRITE REPORT TITLE 01180501 01190501 * 01270501 01320501 BB *** BBCHED0B ******01330501 WRITE DETAIL REPORT HEADERS 01340501 01350501 TO DELETE A TEST USED CODE SHOWN IN TEST 1 01420501 REPLACE THE DELETE COMMENT WITH DELETE CODE 01430501 T001 TEST 1 INTEGER VARIABLE 01440501 05940501 WRITE OUT TEST SUMMARY 06030501 06040501 WRITE OUT REPORT FOOTINGS 06160501 06170501 FORMATS FOR TEST DETAIL LINES 06230501 06240501 FORMATS FOR TEST DETAIL LINES - FULL LANGUAGE 06440501 06450501 FORMAT STATEMENTS FOR PAGE HEADERS 06590501 06600501 06730501 FORMAT STATEMENTS FOR REPORT FOOTINGS 06740501 06750501 06800501 FORMAT STATEMENTS FOR RUN SUMMARY 06810501 06820501 *** 06890501
Arguments
None
Calls
Called by
Contents
Common Blocks
BLK1 BLK2 BLK3 BLK4 BLK5 BLK6
Common Blocks
common /BLK1/
Type Attributes Name Initial
real :: FXVI
real :: HX2I(2,2)
integer :: IXVI
integer :: KX1I(2)
integer :: MX2I(2,2)
common /BLK2/
Type Attributes Name Initial
real :: AXVS
real :: BXVS
real :: CX2S(2,2)
real :: DZ3S(2,2,2)
real :: EZVS
integer :: JX1S(2)
common /BLK3/
Type Attributes Name Initial
real :: AX1D(2)
real :: BX4D
real :: RXVD
common /BLK4/
Type Attributes Name Initial
real :: AXVC
real :: BX1C(2)
real :: CZ5C(2,2,2,2,2)
common /BLK5/
Type Attributes Name Initial
real :: AXVB
real :: BZ1B(2)
real :: CX6B
common /BLK6/
**** 00530501
Type Attributes Name Initial
real :: A1XVK
real :: B1X1K(2)
real :: C1X7K(2,2,2,2,2,2,2)
real :: D2Z1K(2)
real :: E4XVK
real :: G4X2K(2,2)
integer :: I10XVK
real :: S2XVK
Call graph
sn501 calls mx2i, kx1i, dz3s, 2, cx2s, hx2i
fm500 calls sn501